/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d8e2ff",
        "tertiary-fixed": "#e8deff",
        "on-secondary-fixed-variant": "#004494",
        "on-secondary-fixed": "#001a41",
        "secondary": "#adc6ff",
        "on-tertiary-fixed-variant": "#4f00d0",
        "tertiary-fixed-dim": "#cdbdff",
        "surface-container-lowest": "#0a0e14",
        "tertiary-container": "#a387ff",
        "on-tertiary-container": "#39009a",
        "on-primary-fixed-variant": "#832600",
        "on-surface": "#dfe2eb",
        "on-tertiary-fixed": "#20005f",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-variant": "#31353c",
        "error": "#ffb4ab",
        "on-background": "#dfe2eb",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary": "#cdbdff",
        "outline-variant": "#594139",
        "on-primary-container": "#5f1a00",
        "inverse-on-surface": "#2d3137",
        "surface-bright": "#353940",
        "on-primary": "#5d1900",
        "on-primary-fixed": "#390c00",
        "surface-container-low": "#181c22",
        "primary-fixed-dim": "#ffb59d",
        "surface": "#10141a",
        "primary-fixed": "#ffdbd0",
        "on-secondary-container": "#dae4ff",
        "inverse-primary": "#ac3500",
        "on-error": "#690005",
        "outline": "#a88a81",
        "primary-container": "#ff6c37",
        "primary": "#ffb59d",
        "background": "#10141a",
        "on-tertiary": "#370096",
        "surface-tint": "#ffb59d",
        "surface-container": "#1c2026",
        "secondary-container": "#0162cf",
        "surface-container-high": "#262a31",
        "inverse-surface": "#dfe2eb",
        "surface-dim": "#10141a",
        "surface-container-highest": "#31353c",
        "on-surface-variant": "#e1bfb5",
        "on-secondary": "#002e69"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body": ["Manrope", "Inter", "sans-serif"],
        "label": ["Manrope", "Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
}
